<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Тест логина</title>
</head>
<body>
<h1>Страница логина JTE работает</h1>
<form method="post" action="/login">
    <div>
        <label>Имя пользователя:
            <input type="text" name="username">
        </label>
    </div>
    <div>
        <label>Пароль:
            <input type="password" name="password">
        </label>
    </div>
    <button type="submit">Войти</button>
</form>
</body>
</html>
